spring.application.name=location-api
server.port=8070

# MongoDB Pruebas
spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI}

# Eureka Client
eureka.instance.hostname=eureka-server
eureka.client.service-url.defaultZone=http://${eureka.instance.hostname}:8761/eureka/
eureka.instance.prefer-ip-address=true

# Cloudflare R2 Configuration
spring.cloud.aws.s3.endpoint=${SPRING_CLOUD_AWS_S3_ENDPOINT}
spring.cloud.aws.region.static=auto
spring.cloud.aws.credentials.access-key=${SPRING_CLOUD_AWS_CREDENTIALS_ACCESS_KEY}
spring.cloud.aws.credentials.secret-key=${SPRING_CLOUD_AWS_CREDENTIALS_SECRET_KEY}
spring.cloud.aws.s3.bucket-name=${SPRING_CLOUD_AWS_S3_BUCKET_NAME}
cloudflare.r2.project=${CLOUDFLARE_R2_PROJECT}

jwt.secret=${JWT_SECRET}
jwt.secret.refresh=${JWT_SECRET_REFRESH}
spring.security.oauth2.resourceserver.jwt.jws-algorithms=${SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWS_ALGORITHMS}


google.maps.api.key=${GOOGLE_MAPS_API_KEY}
spring.cloud.gcp.pubsub.credentials.location=file:/app/gcp-credentials.json
spring.cloud.gcp.project-id=${SPRING_CLOUD_GCP_PROJECT_ID}
spring.cloud.gcp.vision.enabled=true
spring.cloud.gcp.vision.credentials.default-scopes=https://www.googleapis.com/auth/cloud-platform